### ISSUE TITLE
stick on top

### ISSUE THREAD

**Issue by pishguy** [aryzhov/flutter-stopper#2]
hi, thank a lot to release this useful library

i have a simple issue as, how can i know stopper stick on top such as appBar?

**Comment by aryzhov** [comment]
Currently, the only place where you can see the current position of the stopper is the builder. I guess I could expose the state such that you can attach a listener.  Can you describe your use case scenario?

**Comment by pishguy** [comment]
@aryzhov i think `stop` in `builder` can be provide that, is this right?

**Comment by aryzhov** [comment]
Yes, that's correct.
